# rabbit configuration
kuhnen.rabbit.user: admin
kuhnen.rabbit.password: admin
kuhnen.rabbit.vhost: localhost
#
#  # logging level
logging.level.org.springframework: ERROR
logging.level.com.mkyong: DEBUG